import React, { useEffect, useState } from "react";
import { motion } from "framer-motion";
import { useNavigate } from "react-router-dom";

export default function CommunityRecipes() {
  const navigate = useNavigate();
  const [recipes, setRecipes] = useState([]);
  const [ingredientSymbols, setIngredientSymbols] = useState({});

  useEffect(() => {
    fetch("http://localhost:8080/api/explore")
      .then(res => res.json())
      .then(data => setRecipes(data))
      .catch(console.error);

    fetch("http://localhost:8080/ingredients")
      .then(res => res.json())
      .then(data => {
        const lookup = {};
        data.forEach(item => {
          if (item.name && item.symbol) {
            lookup[item.name.toLowerCase()] = item.symbol;
          }
        });
        setIngredientSymbols(lookup);
      })
      .catch(console.error);
  }, []);

  const getIngredientDetails = (ingredient) => {
    if (typeof ingredient === "object" && ingredient.name) {
      return { name: ingredient.name, symbol: ingredient.symbol || ingredientSymbols[ingredient.name.toLowerCase()] || "🥘" };
    }
    return { name: "Unknown", symbol: "🥘" };
  };

  return (
    <section className="relative w-full py-24 overflow-hidden font-sans">
      <div className="absolute inset-0 z-0 pointer-events-none">
        <div
          className="absolute inset-0 opacity-[0.4]"
          style={{
            backgroundImage: `linear-gradient(to right, #e5e7eb 1px, transparent 1px),
                              linear-gradient(to bottom, #e5e7eb 1px, transparent 1px)`,
            backgroundSize: "40px 40px",
          }}
        ></div>
        <div className="absolute top-1/3 left-0 w-[400px] h-[400px] bg-purple-200/30 rounded-full blur-[100px] mix-blend-multiply"></div>
        <div className="absolute bottom-0 right-0 w-[500px] h-[500px] bg-blue-100/30 rounded-full blur-[100px] mix-blend-multiply"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-6">
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold tracking-tight mb-4">
            <span className="bg-gradient-to-r from-purple-600 to-fuchsia-600 bg-clip-text text-transparent">
              Community Creations
            </span>
          </h2>
          <p className="text-lg text-gray-600 max-w-2xl mx-auto">
            Discover the latest recipes generated by our community using AI.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {[...recipes].reverse().slice(0, 4).map((recipe, index) => {
            const ingredients = recipe.ingredientList || [];

            return (
              <motion.div
                key={recipe.id || index}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.2 }}
                viewport={{ once: true }}
                className="group flex flex-col p-6 rounded-3xl bg-white/40 backdrop-blur-xl border border-white/60 shadow-[0_4px_20px_rgba(0,0,0,0.03)] hover:shadow-[0_8px_30px_rgba(0,0,0,0.08)] hover:-translate-y-2 transition-all duration-300"
              >
                <div className="mb-4">
                  <h3
                    className="text-xl font-bold text-gray-900 leading-tight group-hover:text-purple-700 cursor-pointer line-clamp-2 mb-1"
                    onClick={() => navigate(`/recipes/${recipe.id}`)}
                  >
                    {recipe.title}
                  </h3>
                  <p className="text-xs text-gray-400 font-medium">
                    by {recipe.authorName || "Anonymous"}
                  </p>
                </div>

                <p className="text-gray-600 text-sm leading-relaxed mb-6 line-clamp-3 flex-grow">
                  {recipe.instructions.slice(0, 69)}
                </p>

                <div className="flex flex-wrap gap-2 mt-auto">
                  {ingredients.slice(0, 3).map((ingredient, idx) => {
                    const details = getIngredientDetails(ingredient);
                    return (
                      <span
                        key={idx}
                        className="flex items-center gap-1 px-2.5 py-1 rounded-md bg-white border text-xs font-medium text-gray-600 shadow-[0_2px_6px_rgba(0,0,0,0.05)]"
                      >
                        <span className="text-sm">{details.symbol}</span>
                        <span>{details.name}</span>
                      </span>
                    );
                  })}
                  {ingredients.length > 3 && (
                    <span className="px-2.5 py-1 rounded-md bg-purple-50 text-xs font-medium text-purple-600 border">
                      +{ingredients.length - 3} more
                    </span>
                  )}
                </div>
              </motion.div>
            );
          })}
        </div>

        <div className="flex justify-center">
          <a
            href="/explore"
            className="group inline-flex items-center justify-center px-8 py-4 font-semibold text-white bg-gray-900 rounded-2xl hover:bg-gray-800 hover:scale-105 hover:shadow-lg transition-all duration-200"
          >
            <span>View All Recipes</span>
            <svg className="w-5 h-5 ml-2 -mr-1 transition-transform group-hover:translate-x-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M13 7l5 5m0 0l-5 5m5-5H6" />
            </svg>
          </a>
        </div>
      </div>
    </section>
  );
}
